import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layouts/layout";
import { useSession } from "next-auth/react";
import axios from "axios";
import { useEffect, useState } from "react";
import { fetcher } from "@/lib/api";
import Link from 'next/link';

export default function Profile(props) {

  const { data: session, status } = useSession();
  console.log(session);
  const jwtToken= session ? session.jwt : null;
  const [user , setUser] = useState("");

    useEffect( ()=> {
      const check =  async () => {
        const res =  await fetch(`${process.env.NEXT_PUBLIC_STRAPI_URL}/users/me`, {
          method: 'GET',
          headers: { Authorization:`Bearer ${jwtToken}` }
        })
        const user =  await res.json();
        setUser(user);
      }
      check();
    },[jwtToken]);
  console.log(user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App  {user.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
      <div className="container">
      
      
      <div class="md:flex bg-slate-100 rounded-xl p-8 md:p-10">
        
          
        <div class="relative overflow-x-auto">
            <h1 class="text-sky-500 dark:text-sky-400 py-2">
            Welllcome back {user.username}
            </h1>

            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            User name
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Email
                        </th>
                        <th scope="col" class="px-6 py-3">
                        Phone
                        </th>
                        
                        <th scope="col" class="px-6 py-3">
                          CreatedAt
                        </th>
                        <th scope="col" class="py-3">
                            STATUS
                        </th>
                        <th scope="col" class="px-2 py-3">
                          Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr className="bg-white border-b
                            dark:bg-gray-800 dark:border-gray-700 rounded-3xl">
                        <th scope="row" class="uppercase px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {user.username}
                        </th>
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {user.email}
                        </th>
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {user.phone}
                        </th>
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {user.createdAt}
                        </th>
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {user.confirmed == true ? 'Active' : 'inActive' }
                        </th>

                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        <Link href="/ForgotPassword" className="hover:text-blue-600 px-6">    
                        ForgotPassword
                         </Link>
                         <Link href="/ResetPassword" className="hover:text-blue-600 px-6">    
                         Reset Password
                         </Link>
                        </th>
                        
                    </tr>
                    
                </tbody>
            </table>
        </div>

        </div>
    </div>

      </Layout>
    </div>
    
  ); 
}

